[project]
name = "ace"
version = "0.1.0"
description = "Become the Ace of SPLADEs"
readme = "README.md"
requires-python = ">=3.12"
packages = [
    { include = "ace_of_splades", from = "src" },
]
dependencies = [
    "fastparquet>=2024.11.0",
    "jupyterlab>=4.3.4",
    "lancedb>=0.18.0",
    "polars>=1.19.0",
    "pyarrow>=18.1.0",
    "sentence-transformers>=3.3.1",
]
